### ISSUE TITLE
move config definition and services directly into the bundle source, add tags

### ISSUE THREAD

**Issue by tacman** [yceruto/bundle-flex#3]
Since AbstractBundle allows the configuration and containerBuilder right in the class bundle, I think it'd be nice to have those definitions there, rather than spread out (as was required before Symfony 6.1).

It'd also be great to have the controller added right to the configuration, with the tags already applied.

```php
        $builder->autowire(MyBundleController::class)
            ->addTag('container.service_subscriber')
            ->addTag('controller.service_arguments')
            ->setAutoconfigured(true)
            ->setAutowired(true)
            ->setPublic(true)
        ;
```

**Comment by yceruto** [comment]
>Since AbstractBundle allows the configuration and containerBuilder right in the class bundle, I think it'd be nice to have those definitions there, rather than spread out (as was required before Symfony 6.1).

Can you provide a code example of what you mean?

**Comment by yceruto** [comment]
>It'd also be great to have the controller added right to the configuration, with the tags already applied.

I'd rather update the controller template to extend from `AbstractController` and then register this controller with autowire and autoconfigure only. That would be enough to set up the needed tags.

**Comment by tacman** [comment]
Instead of creating a separate file for the definition, simply add these methods:

```php

class MyBundle extends AbstractBundle
{
    protected string $extensionAlias = 'my_bundle';

    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $definition = $builder
            ->autowire('my.bundle_twig', MyBundleTwigExtension::class)
            ->addTag('twig.extension');


        $definition = $builder->autowire(MyCommand::class)
            ->setAutoconfigured(true)
            ->setArgument('$entityManager', new Reference('doctrine.orm.entity_manager'))
            ->addTag('console.command')
        ;

    }

    public function configure(DefinitionConfigurator $definition): void
    {
        // since the configuration is short, we can add it here
        $definition->rootNode()
            ->children()
            ->scalarNode('foregroundColor')->defaultValue('green')->end()
            ->end();
        ;
    }
```

You can even add the CompilerPass 

```php
class MyBundle extends AbstractBundle implements CompilerPassInterface
{

    public function process(ContainerBuilder $container): void
    { 
        // act on attributes or whatever the compiler pass needs to do.
    }

**Comment by yceruto** [comment]
Yes, I know, but I still prefer the current way as the default because your bundle can grow over time, and then having all the definitions in the bundle class will be a mess. Anyway, it will be pretty simple to go to the simplified version with an all-in-one class if you consider your bundle very small.
